SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_FPS = 120

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 500
PLAYER_SPEED_CAP = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_DELAY = 0.6
PLAYER_MASS = 1

SHOT_RADIUS = 5